import {
  Layers,
  Activity,
  Box,
  Maximize,
  GitCommit,
  Menu,
  CircleDashed,
  Sliders,
  type LucideIcon,
} from "lucide-react";
import { LayerType } from "../types";

export const LAYER_LABELS: Record<LayerType, string> = {
  conv2d: "Conv2D",
  conv3d: "Conv3D",
  relu: "ReLU",
  sigmoid: "Sigmoid",
  tanh: "Tanh",
  leaky_relu: "Leaky ReLU",
  elu: "ELU",
  gelu: "GELU",
  group: "Group",
  maxpool2d: "MaxPool2D",
  maxpool3d: "MaxPool3D",
  linear: "Linear",
  flatten: "Flatten",
  dropout: "Dropout",
  batchnorm2d: "BatchNorm2D",
  batchnorm3d: "BatchNorm3D",
};

export const LAYER_ICONS: Record<LayerType, LucideIcon> = {
  conv2d: Layers,
  conv3d: Layers,
  relu: Activity,
  sigmoid: Activity,
  tanh: Activity,
  leaky_relu: Activity,
  elu: Activity,
  gelu: Activity,
  group: Box,
  maxpool2d: Maximize,
  maxpool3d: Maximize,
  linear: GitCommit,
  flatten: Menu,
  dropout: CircleDashed,
  batchnorm2d: Sliders,
  batchnorm3d: Sliders,
};

export const LAYER_COLOR_CLASS: Record<LayerType, string> = {
  conv2d: "text-indigo-400",
  conv3d: "text-indigo-400",
  relu: "text-emerald-400",
  sigmoid: "text-emerald-400",
  tanh: "text-emerald-400",
  leaky_relu: "text-emerald-400",
  elu: "text-emerald-400",
  gelu: "text-emerald-400",
  group: "text-blue-400",
  maxpool2d: "text-orange-400",
  maxpool3d: "text-orange-400",
  linear: "text-purple-400",
  flatten: "text-purple-400",
  dropout: "text-red-400",
  batchnorm2d: "text-cyan-400",
  batchnorm3d: "text-cyan-400",
};
